version: "3.9"

services:
  backend:
    build: ./ml_api
    container_name: ufc-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./web-app
    container_name: ufc-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
